# Generated by Django 5.0.7 on 2024-07-30 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves_count', models.IntegerField(default=0, verbose_name='Moves Count')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('mode', models.CharField(choices=[('classic', 'Classic')], default='classic', max_length=50, verbose_name='Mode')),
                ('moves', models.TextField(blank=True, null=True, verbose_name='Moves')),
                ('matrix', models.TextField(blank=True, null=True, verbose_name='Matrix')),
                ('players', models.ManyToManyField(related_name='game', to=settings.AUTH_USER_MODEL, verbose_name='Players')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
