# Generated by Django 5.0.7 on 2024-07-30 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Searching since')),
                ('mode', models.CharField(choices=[('classic', 'Classic')], default='classic', max_length=50, verbose_name='Mode')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lobby', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'verbose_name': 'lobby',
                'verbose_name_plural': 'lobbies',
            },
        ),
    ]
