# Generated by Django 5.0.7 on 2024-08-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_lobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='black_id',
            field=models.IntegerField(default=8, verbose_name='Black Player ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='white_id',
            field=models.IntegerField(default=8, verbose_name='White Player ID'),
            preserve_default=False,
        ),
    ]
